### ISSUE TITLE
Menu "More" options hidden behind the header

### ISSUE THREAD

**Issue by daviddiz** [Elghard/Odoo-App#4]
When I scroll down and select a record from the list, the "More" menu options are behind the header.
Tested in Firefox 50 and Chrome 47.
![header sticky](https://cloud.githubusercontent.com/assets/1212657/22104662/aab92ec0-de40-11e6-8bf9-13efaa0cca6f.png)

**Comment by daviddiz** [comment]
Solution:
in module web:  static/src/css/base.css

change "z-index" to 4

705     .openerp .oe_dropdown_menu {
706                   display: none;
707                   position: absolute;
708                   z-index: 4;

**Comment by Elghard** [comment]
Actually I have commit change on sticky_table_headers.js:144. Please download the new one.
For Version 9 and 10 are still in development.
